# Generated by Django 5.1.3 on 2025-02-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0002_remove_comment_book_remove_comment_username_food_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Course',
        ),
    ]
