# Generated by Django 5.1.3 on 2025-02-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_app', '0003_rename_food_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Theme',
        ),
    ]
